apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
      - image: e7asticp7astic/log-output:0.1
        imagePullPolicy: IfNotPresent
        name: log-output
        resources: {}